-- SCHEMA: public

-- DROP SCHEMA pocket CASCADE;

CREATE SCHEMA pocket
    AUTHORIZATION postgres;

COMMENT ON SCHEMA pocket
    IS 'chat-java-backend';

GRANT ALL ON SCHEMA pocket TO postgres;

GRANT ALL ON SCHEMA pocket TO admin;

GRANT USAGE ON SCHEMA pocket TO "user";

ALTER DEFAULT PRIVILEGES IN SCHEMA pocket
GRANT ALL ON TABLES TO admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA pocket
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLES TO "user";

ALTER DEFAULT PRIVILEGES IN SCHEMA pocket
GRANT SELECT, USAGE ON SEQUENCES TO admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA pocket
GRANT EXECUTE ON FUNCTIONS TO admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA pocket
GRANT USAGE ON TYPES TO admin;

SET search_path TO pocket, public;

