package ru.geekbrains.pocket.backend.util;

public class Constant {
    public static final String EXAMPLE_TOKEN = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwZXRyQG1haWwucnUiLCJzY29wZXMiOlt7ImlkIjoyLCJjcmVhdGVkT24iOjE1NTY0NDc3MDA3NjYsInVwZGF0ZWRPbiI6MTU1NjQ0NzcwMDc2NiwibmFtZSI6Iklubm92YXRvciIsImRlc2NyaXB0aW9uIjoi0J3QvtCy0LDRgtC-0YAiLCJuZXciOmZhbHNlfV0sImlzcyI6Imh0dHA6Ly9qc2NvcnAucnUiLCJpYXQiOjE1NTY0NDc3MDIsImV4cCI6MTU1OTAzOTcwMn0.Pu47JWJM-vm0LgIvP9h_QbpAzgj_U_u7l1tCBMP04kY";

}
